let today = moment();
let today1 = today.add(15, 'weeks');
let todaysubtr = moment();
let todayStart = moment().startOf('year');
let todayEnd = moment().endOf('week');
let today3 = todaysubtr.subtract(15, 'weeks');
let todayBlrLoc = moment().locale('be').format('LLLL');
let fromNow = (moment([2019, 11, 17, 16]).fromNow());
let toNow = (moment([2019, 11, 17, 16]).toNow());
let calendar = moment([2019, 11, 16]).calendar();
let duration = moment.duration(100000000000).as('years');
let duration1 = moment.duration(100000000000).humanize();
console.log(today.format('YYYY-MMMM-Do'));
console.log(today.format('LLLL'));
console.log(today.get('year'));
console.log(today.get('month'));
console.log(today.get('date'));
console.log(today.get('hour'));
console.log(today.get('minute'));
console.log(today.get('second'));
console.log(today.get('millisecond'));
console.log(today1._d);
console.log(today3._d);
console.log(todayStart._d);
console.log(todayEnd._d);
console.log(todayBlrLoc);
console.log(fromNow);
console.log(toNow);
console.log(calendar);
console.log(duration);
console.log(duration1);